### ISSUE TITLE
Can we have a nuget package?

### ISSUE THREAD

**Issue by mjtpena** [rabbitmq/rabbitmq-stream-dotnet-client#1]
Hi! Excellent work. I'm really liking the implementation so far.

How can I assist on this project? 

Also, maybe we can create a nuget package as an alpha release.

**Comment by kjnilsson** [comment]
Thanks. I’m away for a few days. When I get back I could start creating issues of specific things to implement but until then some scripts to create a nuget package would be useful.

**Comment by mjtpena** [comment]
Added a simple PR with notes. Let me know how you want to proceed with it.

**Comment by CasperTDK** [comment]
Yes please create an overview. I am very interested in using the sdk, and happy to support development

**Comment by kjnilsson** [comment]
@mjtpena Ive merged the PR - thanks!  would you mind handing over ownership of the package you published to the `team-rabbitmq` user on nuget?

**Comment by mjtpena** [comment]
Added "team-rabbitmq" as the owner! :)
Once it's approved, I'm happy to leave.

btw, the action pulls a secret from your team's environment settings.

**Comment by kjnilsson** [comment]
Ok it is working :)

https://www.nuget.org/packages/RabbitMQ.Stream.Client/0.0.1-pre.1

Thanks1
