### ISSUE TITLE
Issues with correlation

### ISSUE THREAD

**Issue by CasperTDK** [rabbitmq/rabbitmq-stream-dotnet-client#10]
When I am running a more complex setup with multiple threads or outstanding requests, I am getting correlation issues.

This seems suspicious to me:
https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/main/RabbitMQ.Stream.Client/ICommand.cs#L9

Shouldn't CorrelationId always be exposed?

Otherwise I believe https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/main/RabbitMQ.Stream.Client/Client.cs#L253-L261

Will just return the first submitted request response, if there has been a timing issue

**Comment by CasperTDK** [comment]
This has happened in my ClientFactory, where I have bad correlation between my client commands (publish/subscribe) and the QueryMetaData request in the factory.

```
{System.InvalidCastException: Unable to cast object of type 'RabbitMQ.Stream.Client.QueryPublisherResponse' to type 'RabbitMQ.Stream.Client.MetaDataResponse'.
   at RabbitMQ.Stream.Client.Client.QueryMetadata(String[] streams)
   at OCI.DataConsumer.Infrastructure.Installers.StreamClientFactory.GetClient() in C:\projects\omnia.oci\oci.dataconsumer\OCI.DataConsumer\Infrastructure\Installers\StreamClientInstaller.cs:line 52}
```

**Comment by kjnilsson** [comment]
I think these two lines should be using command.CorrelationId instead

https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/main/RabbitMQ.Stream.Client/Client.cs#L280-L281

**Comment by kjnilsson** [comment]
I will push a fix for that

**Comment by kjnilsson** [comment]
Ok pull latests and try

**Comment by CasperTDK** [comment]
OK, let me know when you have bumped the version on nuget :)

**Comment by CasperTDK** [comment]
Wouldn't my MR still be relevant, or am I misunderstanding how correlationIds are used?

**Comment by kjnilsson** [comment]
Because the interface exposes a default CorrelationId value we don't need to implement it for every ICommand, only those that are actually correlated so I don't think your PR fixes anything.

**Comment by kjnilsson** [comment]
are we ok with this issue after the fix?

**Comment by CasperTDK** [comment]
Let me double check tonight - roughly in 3 hours

**Comment by CasperTDK** [comment]
@kjnilsson Your fix did the trick!
