### ISSUE TITLE
Evaluate use of Wait vs await

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-stream-dotnet-client#106]
Also, use of `CancellationToken` for long-running tasks.

See this discussion:
https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/104/files#r854652659

**Comment by Hawxy** [comment]
I just stumbled upon this as I was looking at the producer implementation. You don't really want to use `Wait()` in any modern .NET as it's a sync-over-async wait (see [David Fowler's async guidance](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#avoid-using-taskresult-and-taskwait)). Given this project targets .NET 6, the new `WaitAsync` is available and a preferrable solution.

I noticed a `Wait` has snuck into the [heartbeat timer](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/86f924d4b966b5499f134a81c81acfdc192efa95/RabbitMQ.Stream.Client/HeartBeatHandler.cs#L38) which is also [advised against](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#timer-callbacks). The new periodic timer added in .NET 6 might be useful there.

**Comment by Gsantomaggio** [comment]
Thank you @Hawxy for your comment.
Feel free to open a PR to improve it.

**Comment by Gsantomaggio** [comment]
closed  via https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/206, https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/230/files#diff-7b6d3c170b1f46c840a8ebdc5b44d4f190e8c2a7c6cdc3d071615080c7846916R166 and https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/231
