### ISSUE TITLE
Check out System.Threading.Channels

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-stream-dotnet-client#107]
https://devblogs.microsoft.com/dotnet/an-introduction-to-system-threading-channels/

At first glance it seems to do the same thing as `ConfirmationPipe` in #104

**Comment by stebet** [comment]
Channels would probably be an excellent fit for this purpose, since messages can be put back on the channel in case of failure. I think the latest versions of the channels also have Peek* operations.

**Comment by Gsantomaggio** [comment]
I did some tests and in this case there no too much difference between `channels` and `TPL`. TPL seems to be a bit faster but the main problem here is the [Dictionary Access]( https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/rproducer/RabbitMQ.Stream.Client/Reliable/ConfirmationPipe.cs#L53) .

TPL also it is a bit easier to handle. 

I am going to close the issue and leave the current implementation.
