### ISSUE TITLE
System.Net.Sockets.SocketException: 'No such host is known.'

### ISSUE THREAD

**Issue by yujie-zhou** [rabbitmq/rabbitmq-stream-dotnet-client#114]
Hi all,

I was following the documentation and was running into this error when it comes to creating producer:
![image](https://user-images.githubusercontent.com/91549994/166072688-de87554f-78d9-4feb-9ff9-4a08976ad9eb.png)

Error message:
![image](https://user-images.githubusercontent.com/91549994/166074333-b0a724e2-ac4c-4144-871e-57b126ecfb90.png)

Here's my config:
```
var config = new StreamSystemConfig
{
    UserName = "guest",
    Password = "guest",
    VirtualHost = "/",
    Endpoints = new List<EndPoint> { new IPEndPoint(IPAddress.Parse("127.0.0.1"), 5552) },
};
```

I also looked into the connection properties: 
![image](https://user-images.githubusercontent.com/91549994/166072906-b94d7b31-0728-48d1-8d1e-8ce7abcb1d9d.png)

The advertised host is matching a part of the node name displayed in management UI:
![image](https://user-images.githubusercontent.com/91549994/166073142-5fb4c3ef-2603-45fa-91bf-1bb22431f591.png)

Is this related to the advertised host not being recognized? I'm using docker to run RabbitMQ and has enabled stream plugin, but don't know how to set advertised host with it.

Any idea on what should I do to fix it?

Thank you!

**Comment by Gsantomaggio** [comment]
Hi,

you need to use the `advertised_host localhost` in this way:
```shell

docker run -it --rm --name my-rabbitmq \
                -p 5552:5552 -p 5672:5672 -p 15672:15672 \
                -e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbitmq_stream advertised_host localhost" \
                <<my_rabbitmq_docker_image>>
```

**Comment by yujie-zhou** [comment]
> Hi,
> 
> you need to use the `advertised_host localhost` in this way:
> 
> ```shell
> docker run -it --rm --name my-rabbitmq \
>                 -p 5552:5552 -p 5672:5672 -p 15672:15672 \
>                 -e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbitmq_stream advertised_host localhost" \
>                 <<my_rabbitmq_docker_image>>
> ```

That solved my problem. Thank you so much!
