### ISSUE TITLE
DNS check when using loadbalancer with AddressResolver

### ISSUE THREAD

**Issue by johanneshall** [rabbitmq/rabbitmq-stream-dotnet-client#125]
In the class RoutingClient there is a DNS check on line [52](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/62217deb66e494f57c492110291631d315a9e0f2/RabbitMQ.Stream.Client/RoutingClient.cs#L51) when using a load balancer with AddressResolver.
If the hostname can not be found the DNS check fails and throws an exception. This happens when running in docker with internal hostnames.

As the endpoint created is only used inside the next if statement and overwritten after it this check should probably be performed inside that if statement.

**Comment by Gsantomaggio** [comment]
Thank you for reporting @johanneshall 
Do you have a way to reproduce the issue? maybe using some docker-compose.

**Comment by johanneshall** [comment]
The setup we are using is quite complex and not really suitable for reproducing the issue.
The simplest way to reproducing it should be to set the hostname of the rabbitmq server to something that the client can't find in DNS and use a AddressResolver.

Problem is the lines:
```
if (routing.ValidateDns)
{
    var hostEntry = await Dns.GetHostEntryAsync(broker.Host);
    endPoint = new IPEndPoint(hostEntry.AddressList.First(), (int)broker.Port);
}
```

This always gets called and if the DNS entry is not found we get a "System.Net.Sockets.SocketException: 'No such host is known.'" when calling Dns.GetHostEntryAsync
In my case "broker.Host" is "rabbitmq2"

When using the AddressResolver the endPoint created above is overwritten so there is no need to do the DNS lookup in the first place:
`endPoint = clientParameters.AddressResolver.EndPoint;`

What I did was change

```
if (routing.ValidateDns)
{
    var hostEntry = await Dns.GetHostEntryAsync(broker.Host);
    endPoint = new IPEndPoint(hostEntry.AddressList.First(), (int)broker.Port);
}

if (clientParameters.AddressResolver == null
    || clientParameters.AddressResolver.Enabled == false)
{
    // In this case we just return the node (leader for producer, random for consumer)
    // since there is not load balancer configuration

    return routing.CreateClient(clientParameters with { Endpoint = endPoint });
}
```
to
```
if (clientParameters.AddressResolver == null
    || clientParameters.AddressResolver.Enabled == false)
{
    if (routing.ValidateDns)
    {
        var hostEntry = await Dns.GetHostEntryAsync(broker.Host);
        endPoint = new IPEndPoint(hostEntry.AddressList.First(), (int)broker.Port);
    }

    // In this case we just return the node (leader for producer, random for consumer)
    // since there is not load balancer configuration
    return routing.CreateClient(clientParameters with { Endpoint = endPoint });
}
```

I have not checked if this breaks anything else but from my reading of the code it should probably not.

**Comment by Gsantomaggio** [comment]
@johanneshall https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/126 :)

**Comment by Gsantomaggio** [comment]
@johanneshall https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/releases/tag/v1.0.0-rc.3

[NuGet](https://www.nuget.org/packages/RabbitMQ.Stream.Client/) should be ready in a few minutes 

Let me know
