### ISSUE TITLE
StreamSystemConfig: should you be allowed to provide both LB and endpoints?

### ISSUE THREAD

**Issue by ricsiLT** [rabbitmq/rabbitmq-stream-dotnet-client#127]
Had a question about design of StreamSystemConfig - should it even be possible to have both AddressResolver and Endpoints?
The way I see it, if you provide an AddressResolver, the endpoint list is implicitly the endpoint of that AddressResolver. If you provide endpoints and an AddressResolver, what's the use for LB? Wanted to create a PR to check for this but I think I'm just missing something.

**Comment by lukebakken** [comment]
I'll have to review the code to answer your question, but there's never a problem with submitting PRs! We're always happy to take a look.

**Comment by Gsantomaggio** [comment]
@lukebakken copied from java: https://blog.rabbitmq.com/posts/2021/07/connecting-to-streams/ 
```
Using the Stream Java Client With a Load Balancer
```

**Comment by ricardSiliuk** [comment]
https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/129

**Comment by lukebakken** [comment]
https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/129#issuecomment-1140890009
