### ISSUE TITLE
Request for awaitable batch publish

### ISSUE THREAD

**Issue by ricsiLT** [rabbitmq/rabbitmq-stream-dotnet-client#136]
Hi,

We are implementing a publisher extension like that right now but maybe it would be useful for more users of the library.

The only firm requirements we have is 

* every message has to have a publishing id (sub-batching isn't an option for us :( )
* we consider failing to deliver any message as a failure/exception

In our implementation, the usage looks more or less like this:

```csharp
var cts = new CancellationTokenSource();
var token = cts.Token;

// reference for producer would be either random or null, since we envision such producer to be disposable.
// Also, it's more simple to think about such producer as single-use
//     * then you don't have to worry about calling `PublishAllMessages` multiple times
//     * and thinking about publishing ids
await using var x = await system.CreateBatchProducer(streamName); 

// publishing should
//     * throw if at least single message failed (not sure how retrying would work - maybe it's possible?)
//     * cancellable
await x.PublishAllMessages(messagesToPublish, token);
```

But since this would be library code, we don't want to push any specific impl, just showcasing how we aim to use it now.

Is it something you'd be looking to add?

**Comment by Gsantomaggio** [comment]
In the GO client, we implemented a specific call  `BatchSend` https://github.com/rabbitmq/rabbitmq-stream-go-client#send-vs-batchsend 

See also: https://github.com/rabbitmq/rabbitmq-stream-go-client/blob/main/examples/performances/performances.go#L80-L82 

Can be something like that ^^ ?

@lukebakken @ricsiLT ?
