### ISSUE TITLE
Unable to create StreamSystem

### ISSUE THREAD

**Issue by TroelsL** [rabbitmq/rabbitmq-stream-dotnet-client#137]
I'm trying to migrate to streams from RabbitMQ.Client, but I'm having difficulties connecting. Can anyone spot anything obvious in what should be equivalent code?

**RabbitMQ.Stream.Client 1.0.0-rc.3**

hostname, username, password, and queue names are defined as string constants and the same values are used in both examples.

Server is cloudamqp.com.

Working RabbitMQ.Client code:
```
var factory = new ConnectionFactory
{
    HostName = hostname,
    UserName = username,
    Password = password
};

var conn = factory.CreateConnection();

var model = conn.CreateModel();
model.BasicQos(0, 10, false);
model.ExchangeDeclare(queueAndExchangeName, ExchangeType.Topic, true, false, new Dictionary<string, object>());
model.QueueDeclare(queueAndExchangeName, true, false, false, new Dictionary<string, object>() { { "x-queue-type", "stream" }, { "x-max-age", "10m" } });
model.QueueBind(queueAndExchangeName, queueAndExchangeName, "Test.#");

var consumer = new EventingBasicConsumer(model);
consumer.Received += Consumer_Received;

void Consumer_Received(object? sender, BasicDeliverEventArgs e)
{
    
}
```

The following throws a `StreamSystemInitialisationException` 'no endpoints could be reached':

```
var system = await StreamSystem.Create(new StreamSystemConfig()
{
    UserName = username,
    Password = password,
    VirtualHost = "/",
    Endpoints = new List<EndPoint>() { new DnsEndPoint(hostname, 5672) }
});
```

**Comment by Gsantomaggio** [comment]
`5672` is the AMQP port. 
Stream clients a different port: `5552`. You need to enable the stream plugin.
For more information see this gist:
-  gist: https://gist.github.com/Gsantomaggio/149b604113bf9d2e044a0f89531c101f
