### ISSUE TITLE
Targeting .NET Standard 2.0 or .NET Standard 2.1

### ISSUE THREAD

**Issue by jdaltonchilders** [rabbitmq/rabbitmq-stream-dotnet-client#143]
Would it be possible also to target [.NET Standard 2.0](https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#select-net-standard-version) similar to [RabbitMQ.Client](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/projects/RabbitMQ.Client/RabbitMQ.Client.csproj#L4)? This would provide compatibility for older applications and help where teams are still needing to support more legacy applications.

**Comment by lukebakken** [comment]
@jdaltonchilders - I created [this branch](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/tree/rabbitmq-stream-dotnet-client-143) to add the same target frameworks as the RabbitMQ AMQP .NET client. As you can see, supporting `netstandard2.0` would require quite a few changes.

@Gsantomaggio @michaelklishin @Zerpet - to reach the largest .NET audience, we _should_ support `netstandard2.0`. Thoughts?

Build output showing errors:

[build-output.txt](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/files/10096597/build-output.txt)

**Comment by lukebakken** [comment]
Also, see this:

https://github.com/npgsql/npgsql/blob/main/src/Npgsql/Npgsql.csproj#L10

**Comment by michaelklishin** [comment]
To be honest, I think this client will primarily be adopted by new applications and thus we can afford to target .NET Standard 2.1. Streams is still a new feature in the community, so I think it'd be quite reasonable for us to target new runtimes and environments with stream clients.

**Comment by lukebakken** [comment]
[.NET Standard 2.0](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0) ensures that people using .NET Framework are supported. .NET Standard 2.1 does not.

**Comment by Zerpet** [comment]
It looks like we are using language features that are not available in .NET Standard 2.0, given the compilation errors in the build output. The project was born targetting .NET 6 IIRC, targetting .NET Standards 2.0 may not be trivial. Another thing to consider is that .NET Framework is a Windows-only technology, and our intention is to support multi-platform .NET, therefore I don't feel too bad for not support .NET Framework.

**Comment by lukebakken** [comment]
I'm pretty sure most of the build errors are for "cosmetic" features. Considering how long .NET Framework [remains in support](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework), I'm going to work on addressing this. If I run into a blocker I will make a note of it here.

**Comment by lukebakken** [comment]
Oof, OK there are much more than cosmetic fixes necessary to use .NET Standard 2.0. I have done a couple hours work and still 700+ errors remain in [my branch](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/tree/rabbitmq-stream-dotnet-client-143).

I am going to see what .NET Standard 2.1 allows.

**Comment by lukebakken** [comment]
I can't really see the benefit of .NET Standard 2.1, either, at least for this library.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/514926/204322430-1ed00534-07c0-4a2d-9520-c5865043aeb6.png">

@jdaltonchilders @ricardSiliuk @ricsiLT - do you have a strong opinion?

I will close this issue for now but it can be re-opened prior to version 1.0.0 if enough people request it. Discussion of course can continue.

**Comment by ricsiLT** [comment]
We initially had this idea that this would be good as a .NET Standard 2.1 or even 2.0 library but looking at where `dotnet` is going plus guidelines on the page where you got the screenshot - it doesn't seem to serve any purpose other than serving really old projects that are stuck, and those can consume via old/AMQP 0.9 client, right? I imagine some features will not be available but that's the price you pay with legacy code?

In that sense, targeting `dotnet6` seems good enough.

**Comment by lukebakken** [comment]
> those can consume via old/AMQP 0.9 client, right?

Yes, that is true. The AMQP .NET project can publish and consume from streams - https://www.rabbitmq.com/streams.html#usage

**Comment by jdaltonchilders** [comment]
@lukebakken Thank you for your patience and for digging in to see what it would have taken to convert the library to .NET Standard 2.0. I agree with the current stance, given the number of changes required to make it compatible.
