### ISSUE TITLE
Load balancer- AddressResolver

### ISSUE THREAD

**Issue by suprunka** [rabbitmq/rabbitmq-stream-dotnet-client#147]
Hi, I consume messages I need to connect by load balanced endpoint.  I use addressresolver, following RbbitMQ documentation (https://blog.rabbitmq.com/posts/2021/07/connecting-to-streams/), but the "advertised_host" property is still incorrect. Therefore I am not able to create consumer/producer. I got "No such host is known".
Shouldn't the advertised_host had load balanced endpoint  name or be empty?

 var endPoint = new IPEndPoint(addresses[0], 5552);
                var lbAddressResolver = new AddressResolver(new IPEndPoint(addresses[0], 5552));
                var config = new StreamSystemConfig
                {
                    UserName = "guest",
                    Password = "guest",
                    VirtualHost = "/",
                    AddressResolver = lbAddressResolver,
                    Endpoints = new List<EndPoint> { lbAddressResolver.EndPoint },
                    ClientProvidedName="stream_consumer"
                };

**Comment by Gsantomaggio** [comment]
@suprunka you haven't provided enough information to understand the problem.
- Can you provide a way to reproduce a problem? 
- How did you configure the servers?
- RabbitMQ version? 
- Client version?



Can you try using this docker-compose?
https://github.com/rabbitmq/rabbitmq-stream-go-client/tree/main/compose
```
git clone git@github.com:rabbitmq/rabbitmq-stream-go-client.git .
make rabbitmq-ha-proxy 
```

Then

```csharp
 var lbAddressResolver = new AddressResolver(new IPEndPoint(IPAddress.Loopback, 5553));
        var config = new StreamSystemConfig()
        {
            AddressResolver = lbAddressResolver,
            Endpoints = new List<EndPoint> {lbAddressResolver.EndPoint},   
        };
```

For more info https://blog.rabbitmq.com/posts/2021/07/connecting-to-streams/#client-workaround-with-a-load-balancer

**Comment by Gsantomaggio** [comment]
solved. See the comment here  https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/148#issuecomment-1179787243
