### ISSUE TITLE
Improve logging when reconnected

### ISSUE THREAD

**Issue by cccp200** [rabbitmq/rabbitmq-stream-dotnet-client#170]
In bug "ReliableProducer not reconnecting after leader goes down" #150 reconnecting was improved when leader went down. There is logging for trying to reconnect, but no logging that reconnect succeeded and actually happened. This additional logging would be useful and appreciated.

**Comment by lukebakken** [comment]
> This additional logging would be useful and appreciated

Please feel free to submit a PR with this additional information. Thanks!

**Comment by Gsantomaggio** [comment]
FYI: you can customize the reconnection behaviour, see [the documentation](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client#reconnection-strategy) and [the test example](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/main/Tests/ReliableTests.cs#L458) 


```csharp
private class MyReconnection : IReconnectStrategy
    {
        ;


        ValueTask<bool> IReconnectStrategy.WhenDisconnected(string info)
        {
          ... wait and log ....
        }

        ValueTask IReconnectStrategy.WhenConnected(string connectionInfo)
        {
        ... wait and log the connections...    
         return ValueTask.CompletedTask;
        }
    }

```
