### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by aeb-dev** [rabbitmq/rabbitmq-stream-dotnet-client#179]
I am trying steams and I think the numbers are not good in my test project. Maybe I am doing something wrong but let me explain the current status:

I have a service that is publishing a json data to stream (normally it is a super stream but I have a single stream currently so ignore that part). Let's call this stream `my-stream`.

I have two consumers that is consuming from `my-stream`.

First one is with this client. Second one is with `java-stream-perf-test` client.
dotnet client has the following configuration:
```
var config = new StreamSystemConfig
{
    Endpoints = new List<EndPoint> { new DnsEndPoint("my-rabbitmq-connection", 5552) },
    UserName = "user",
    Password = "password",
    VirtualHost = "vh",
};

var system = await StreamSystem.Create(config);

await system.CreateStream(new StreamSpec("my-stream")
{
    MaxLengthBytes = 2000000,
});

var consumerStream = await Consumer.Create(
    new ConsumerConfig(system, "my-stream")
    {
        OffsetSpec = new OffsetTypeLast(),
        MessageHandler = (sourceStream, consumer, ctx, message) =>
        {
            return Task.CompletedTask;
        },
    }
);
```

`java-stream-perf-test` is run with the following call:

```
java -jar stream-perf-test.jar --uris rabbitmq-stream://my-rabbitmq-connection --producers 0 --consumers 1 --streams my-stream --offset last
```

While the dotnet client is lagging behind
![image](https://user-images.githubusercontent.com/11612804/200833517-054f410f-5944-4319-bd2e-84ee37bb7e85.png)

The `java-stream-perf-test` was keeping up
![image](https://user-images.githubusercontent.com/11612804/200833594-0b53aef8-d24f-4bd4-9d27-575d3cdf874c.png)

And the average consumption rate of `java-stream-perf-test` is around  5697 msg/s. So I am not actually publishing that much.

So I feel like this client should perform a lot better. Did I configured something wrong? What do you think would be the reason? 

If you need further information I can provide, please ask.

**Comment by Gsantomaggio** [comment]
Thank you for reporting, we will check it

**Comment by Gsantomaggio** [comment]
We maybe found the problem. Working on it ..

**Comment by aeb-dev** [comment]
Btw, I think the publish rate is slow as well. I am not sure whether it is related to this issue or not.

Note: Thanks for the fast response and keeping us updated.

**Comment by Gsantomaggio** [comment]
We identified the bottleneck in the `slice(..)` functions:
https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/a46d95352f930207b4e541705580c6eb99c2630a/RabbitMQ.Stream.Client/Deliver.cs#L66-L68

And also some parts of the AMQP parser that can be improved.

Changing `ReadOnlySequence` to `SequenceReader` improves the performance, but we need to change some core behaviour.
I think we have to do the same for the publishing part.

We are working on it.

**Comment by Gsantomaggio** [comment]
This commit https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/commit/6911edd743b11ee9cafdea4369ab7350311ddf52 solved the consumer performance.

We are working on the publishing side. Once done, we will release a new version.

**Comment by Gsantomaggio** [comment]
With this commit https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/commit/656fcaa08791141e9fe3c262878804a4d3adc6c2 we close the issue. 

Important note:  To speed up the throughput, you can play with the following parameters :
```csharp
 MaxInFlight = 10000,
 MessagesBufferSize = 10000,
```

we just released: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/releases/tag/v1.0.0-rc.7

**Comment by aeb-dev** [comment]
`MessagesBufferSize = 10000,`

I can not set this with high level api

**Comment by lukebakken** [comment]
@aeb-dev please open a new issue instead of commenting on a closed one. Thank you.

**Comment by Gsantomaggio** [comment]
@aeb-dev done via https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/183
