### ISSUE TITLE
Composite consumer does not work

### ISSUE THREAD

**Issue by aeb-dev** [rabbitmq/rabbitmq-stream-dotnet-client#186]
I am trying the example of super stream blog:
https://blog.rabbitmq.com/posts/2022/07/rabbitmq-3-11-feature-preview-super-streams/#overview

and its codebase:
https://github.com/acogoluegnes/rabbitmq-stream-single-active-consumer

However, I am not getting the same result.

Here are the things I did:

- Created partitions:
`docker exec rabbitmq rabbitmq-streams add_super_stream super.stream.test --partitions 3`

- Created two consumers with the following code:
```csharp
await Consumer.Create(
    new ConsumerConfig(system, "super.stream.test")
    {
        Reference = "aa",
        OffsetSpec = new OffsetTypeNext(),
        MessageHandler = (sourceStream, consumer, ctx, message) =>
        {
            Console.WriteLine($"sourcestream: {sourceStream}");
            return Task.CompletedTask;
        },
        IsSingleActiveConsumer = true,
        IsSuperStream = true,
    }
);
```

- Created single producer with the following code:
```csharp
var producer = await Producer.Create(
    new ProducerConfig(system, "super.stream.test")
    {
        SuperStreamConfig = new()
        {
            Enabled = true,
            Routing = (m) =>
            {
                return rand.Next().ToString();
            },
        },
        ConfirmationHandler = confirmation =>
        {
            switch (confirmation.Status)
            {
                // ConfirmationStatus.Confirmed: The message was successfully sent
                case ConfirmationStatus.Confirmed:
                    // Console.WriteLine($"Message {confirmation.PublishingId} confirmed");
                    break;
                // There is an error during the sending of the message
                case ConfirmationStatus.WaitForConfirmation:
                case ConfirmationStatus.ClientTimeoutError
                    : // The client didn't receive the confirmation in time.
                      // but it doesn't mean that the message was not sent
                      // maybe the broker needs more time to confirm the message
                      // see TimeoutMessageAfter in the ProducerConfig
                case ConfirmationStatus.StreamNotAvailable:
                case ConfirmationStatus.InternalError:
                case ConfirmationStatus.AccessRefused:
                case ConfirmationStatus.PreconditionFailed:
                case ConfirmationStatus.PublisherDoesNotExist:
                case ConfirmationStatus.UndefinedError:
                default:
                    Console.WriteLine(
                        $"Message  {confirmation.PublishingId} not confirmed. Error {confirmation.Status}");
                    break;
            }

            return Task.CompletedTask;
        },
    }
);
```

- Send a message every second

```csharp
while (true)
{
    await producer.Send(message);
    await Task.Delay(1000);
}
```

- Run the code above in three separate instances

The result is: Only one instance gets every message

Am I doing something or misunderstood something?

**Comment by aeb-dev** [comment]
If I disable that every consumer gets every message.

The example also uses single active consumer:

https://github.com/acogoluegnes/rabbitmq-stream-single-active-consumer/blob/main/src/main/java/com/rabbitmq/stream/SuperStreamConsumer.java#L23

**Comment by Gsantomaggio** [comment]
@aeb-dev ok found the bug and fixing [here](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/187/files#diff-b08ff9a3d581af9df4f7e209452830c93f2367debb487e937e158870332fbd1eR210-R213). If you have a chance can you please test it?

I need to change some tests with the proper references., but in the meantime is ready for testing

**Comment by aeb-dev** [comment]
It works. Thanks for the fast response!

**Comment by Gsantomaggio** [comment]
@aeb-dev done via https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/commit/20ba4b675b061f32888d8930f99df3af9f5778ea

We will release as soon as possible

**Comment by aeb-dev** [comment]
Is there any news on the release?

**Comment by Gsantomaggio** [comment]
It should be this week. Unless we have some blocking problem.

**Comment by Gsantomaggio** [comment]
@aeb-dev FYI https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/releases/tag/v1.0.0
