### ISSUE TITLE
Implement Sub Entry Batch 

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-stream-dotnet-client#20]
Implement Sub-entry batching.  

from: https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#producer-sub-entry-size-configuration-entry
```
The number of messages to put in a sub-entry. A sub-entry is one "slot" in a publishing frame, 
meaning outbound messages are not only batched in publishing frames, but in sub-entries as well. 
Use this feature to increase throughput at the cost of increased latency and 
potential duplicated messages even when deduplication is enabled.
```

**Comment by CasperTDK** [comment]
What is the equivalent concept in kafka and what is your use-case for this feature? I am curious!

**Comment by Gsantomaggio** [comment]
There should be some a similar feature but I am not sure.

Efficiency and compression are the use cases.

For example, you can decide to aggregate and compress more messages under the same publishing-id.
See the go [client example](https://github.com/rabbitmq/rabbitmq-stream-go-client/blob/main/examples/sub-entries-batching/sub_entries_batching.go#L67-L74) ( In java is the same).

Go and Java support the following compressions:
```golang
NONE = byte(0)
GZIP   = byte(1)
SNAPPY = byte(2)
LZ4    = byte(3)
ZSTD   = byte(4)
```

**Comment by Gsantomaggio** [comment]
depends on https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/34

**Comment by Gsantomaggio** [comment]
Closed via https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/57
