### ISSUE TITLE
Unclosed connections (memoryleak)

### ISSUE THREAD

**Issue by jonnepmyra** [rabbitmq/rabbitmq-stream-dotnet-client#205]
Hi!

We're using streams with shortlived stream-consumers.

Our applications connect at some offset in the stream and read a couple of messages until it closes().

It's not uncommon to see a warning, followed by an error in the logs under the conditions mentioned above. The logs look like:

```
09:25:30.305 [WARN] Received credit response for unknown subscription 0, ResponseCode SubscriptionIdDoesNotExist
09:25:30.300 [ERROR] Error removing the consumer id: 0 from the server
System.TimeoutException: The operation has timed out.
   at RabbitMQ.Stream.Client.RawConsumer.Close()
```

Each of these logged errors, is always followed by a connection not being closed towards RabbitMQ.

The consequence is that the memory footprint is increased in both the client application and on the RabbitMQ Server.

**Comment by Gsantomaggio** [comment]
Thank you for reporting.

Is the bug reproducible in somehow?

Can you please provide a snippet or GitHub repo with the bug so we can test it?

**Comment by jonnepmyra** [comment]
Hi, Thanks for the quick response...

I'll see if I can reproduce in a simple way...

In the meantime, I've added some more debug log to my local fork and figured out that when the unsubscribe command times out and the code continues to close the client,  `conumers == 1` at this location:

https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/ce2e8475cb2c8e916fc3f8fc370b30c1e69b6eae/RabbitMQ.Stream.Client/Client.cs#L575-L578

which could be the reason that the connection is never closed?

**Comment by Gsantomaggio** [comment]
Yes, it could be. 
this error:
`09:25:30.305 [WARN] Received credit response for unknown subscription 0, ResponseCode SubscriptionIdDoesNotExist` means that the subscriber does not exist anymore on the server, but the client sends the credit.

It could happen when the consumer is closing when it still receiving the messages from the stream

**Comment by jonnepmyra** [comment]
Seems like there's some sort of deadlock and the `.GetAwaiter().GetResult()` in the MessageDispatcher which was added in #184 is causing the problem....

If the MessageDispatcher is "reset" to pre-rc8, closing consumers works like a charm.

This "test" could be used to reproduce... (strip the logging part if you want, or add the following nuget packages to get it working)

```
    <PackageReference Include="Divergic.Logging.Xunit" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="7.0.0" />
```

```
       [Fact]
        public async void ReproduceUnClosableConsumers()
        {
            var loggerFactory = LoggerFactory.Create(builder =>
            {
                builder.AddXunit(testOutputHelper);
            });

            var consumerLogger = loggerFactory.CreateLogger<Consumer>();
            var streamLogger = loggerFactory.CreateLogger<StreamSystem>();

            var stream = Guid.NewGuid().ToString();
            var config = new StreamSystemConfig();
            var system = await StreamSystem.Create(config, streamLogger);
            await system.CreateStream(new StreamSpec(stream));

            await SystemUtils.PublishMessages(system, stream, 100000, testOutputHelper);

            var consumer = await system.CreateRawConsumer(
                            new RawConsumerConfig(stream)
                            {
                                Reference = "consumer",
                                OffsetSpec = new OffsetTypeFirst(),
                                MessageHandler = async (consumer, ctx, message) =>
                                {
                                    await Task.Delay(10);
                                }
                            }, consumerLogger);

            //Delay to let the consumers start consuming
            await Task.Delay(300);
            await consumer.Close();

            //Delay to give some time to verify that connection is not closed
            await Task.Delay(TimeSpan.FromSeconds(60));
            await system.DeleteStream(stream);
        }
```

**Comment by Gsantomaggio** [comment]
Thanks @jonnepmyra, that was added for [this reason](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/184#issuecomment-1326154401).

I will try it.

**Comment by Gsantomaggio** [comment]
@jonnepmyra FYI https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/releases/tag/v1.0.1
