### ISSUE TITLE
Target net6.0

### ISSUE THREAD

**Issue by stebet** [rabbitmq/rabbitmq-stream-dotnet-client#24]
Since .NET 6.0 is the latest LTS version, I think this library should target that instead of 5.0. What do you think @kjnilsson?

**Comment by lukebakken** [comment]
https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/main/.github/workflows/test.yaml#L30

**Comment by Gsantomaggio** [comment]
also:
https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/main/RabbitMQ.Stream.Client/RabbitMQ.Stream.Client.csproj#L4
