### ISSUE TITLE
Use DateTimeOffset or use DateTime with DateTimeKind.Utc

### ISSUE THREAD

**Issue by ngbrown** [rabbitmq/rabbitmq-stream-dotnet-client#240]
Since timezone isn't communicated in the AmqpTimestamp, it should be assumed to be Utc. The `WriteTimestamp` writes out the Utc ticks because casting either Local or Utc `DateTime` to `DateTimeOffset` will result in a Utc result from `ToUnixTimeMilliseconds()`:

https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/653cfbe64f1204acc82d456da823c9ee7d32e752/RabbitMQ.Stream.Client/AMQP/AmqpWireFormattingWrite.cs#L224-L230

Similarly, the `ReadTimestamp` should either return `DateTimeOffset` or a `DateTime` with the `UTC` kind set. Instead of this:

https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/653cfbe64f1204acc82d456da823c9ee7d32e752/RabbitMQ.Stream.Client/AMQP/AmqpWireFormattingRead.cs#L157-L161

At a minimum, use:

```cs
value = dateTimeOffset.UtcDateTime; 
```

Even better would be to use `DateTimeOffset` in the public API.

**Comment by lukebakken** [comment]
Feel free to submit a PR.

**Comment by ngbrown** [comment]
@lukebakken Changing the type of `Properties.CreationTime` would be an API breaking change, so how far do you want to go with the change?

**Comment by lukebakken** [comment]
@ngbrown sorry for the delay. We're discussing it internally.

**Comment by lukebakken** [comment]
`dateTimeOffset.UtcDateTime` is the best solution that doesn't require an API change. I'll open a PR.
