### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by CasperTDK** [rabbitmq/rabbitmq-stream-dotnet-client#28]
I would like to update my project to use the consumer and publisher client. Can you publish a new package @kjnilsson or would you like to wait untill something has been resolved or polished

**Comment by Gsantomaggio** [comment]
[Done](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/releases/tag/v0.0.1-pre.5)

**Comment by CasperTDK** [comment]
@Gsantomaggio Nuget.org was not updated :smile:

https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/runs/4379513564?check_suite_focus=true#step:8:16

https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/commit/ee0f9c36bd0709074b77ecad82a6546623d1e2cd#diff-de3d41bfb03c7d027bd047003212ee09a7df0a1ad2452fe0190685b48fcf850fR7

https://www.nuget.org/packages/RabbitMQ.Stream.Client/0.0.1-pre.4

**Comment by CasperTDK** [comment]
It seems it does not use packageversion, but `<version>` in .csproj

**Comment by Gsantomaggio** [comment]
sorry my fault just fixed https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/commit/a2d015a74d6391bbdc9c05eea72775120be86ad5 :) :)

**Comment by Gsantomaggio** [comment]
[It should be ok now](https://www.nuget.org/packages/RabbitMQ.Stream.Client/)
