### ISSUE TITLE
A way to create super stream with `StreamSystem`

### ISSUE THREAD

**Issue by aeb-dev** [rabbitmq/rabbitmq-stream-dotnet-client#297]
### Is your feature request related to a problem? Please describe.

Currently there is no way to create super stream from client. For an application to work properly super stream has to be created beforehand with CLI command. IMO, it would be beneficial to provide such functionality through this client so that applications don't depend on anything

### Describe the solution you'd like

Provide an API for creating a super stream.

```csharp
public class StreamSystem
{
    public async Task CreateSuperStream(SuperStreamSpec spec)
    {
    }
}

public record SuperStreamSpec(string Name, int Partitions) : StreamSpec(Name)
{
    // ....
}
```

**Comment by aeb-dev** [comment]
Got it but it does not have to be handled with 'stream protocol'. The 'stream client' already has something related to AMQP https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/tree/main/RabbitMQ.Stream.Client/AMQP. Can't it be extended to be used to create super stream?

**Comment by Gsantomaggio** [comment]
The .NET stream client ( like the other clients ) implements the [AMQP 1.0](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/tree/main/RabbitMQ.Stream.Client/AMQP) protocol _only_ for the message format. 

The message body for the stream is agnostic, so you can store the message in the format you prefer.
We used the AMQP 1.0 Message format as a lingua franca between the clients. 


For example, the Python client can use AMQP 1.0 as a message format or a binary protocol, see https://github.com/qweeze/rstream#client-performances


AMQP 1.0  Message format <> AMQP 0.9.1 protocol 

I hope it is clear.

**Comment by aeb-dev** [comment]
Yeah it is clear thanks. Two question:
- How does stream client query super stream, I assume it still does not use AMQP?
- Is it possible to declare stream queues with AMQP?

**Comment by Gsantomaggio** [comment]
> How does stream client query super stream, I assume it still does not use AMQP?

No, there is a [specific call](https://github.com/rabbitmq/rabbitmq-server/blob/v3.12.x/deps/rabbitmq_stream/docs/PROTOCOL.adoc#partitions) on the stream protocol 

> Is it possible to declare stream queues with AMQP?

You can use the [stream queues](https://www.rabbitmq.com/streams.html) with AMQP clients connected to the standard AMQP port and the Native clients like this one that uses the [stream plugin](https://www.rabbitmq.com/stream.html)  
See the documentation about [Stream Core vs Stream Plugin](https://www.rabbitmq.com/stream-core-plugin-comparison.html)

**Comment by Gsantomaggio** [comment]
>My question is, can I "declare streams" from amqp


yes, The documentation is clear here: https://www.rabbitmq.com/streams.html#declaring 

> To declare a stream, set the x-queue-type queue argument to stream (the default is classic). This argument must be provided by a client at declaration time; it cannot be set or changed using a [policy](https://www.rabbitmq.com/parameters.html#policies). This is because policy definition or applicable policy can be changed dynamically but queue type cannot. It must be specified at the time of declaration.

> The following snippet shows how to create a stream with the [AMQP 0.9.1 Java client](https://www.rabbitmq.com/api-guide.html):
```java
ConnectionFactory factory = new ConnectionFactory();
Connection connection = factory.newConnection();
Channel channel = connection.createChannel();
channel.queueDeclare(
  "my-stream",
  true,         // durable
  false, false, // not exclusive, not auto-delete
  Collections.singletonMap("x-queue-type", "stream")
);
```


>is there any difference between "declaring streams" from amqp or stream 

No

**Comment by aeb-dev** [comment]
Thanks for the information

**Comment by acogoluegnes** [comment]
@aeb-dev A super stream is just a logical entity, its topology is defined by AMQP 0.9.1 resources (an exchange, queues, and bindings between them). Here is a test utility in the stream Java client that uses AMQP 0.9.1 to declare a super stream: https://github.com/rabbitmq/rabbitmq-stream-java-client/blob/5ad02015c5768d83edf38458f4f3f77bb401e0dc/src/test/java/com/rabbitmq/stream/impl/TestUtils.java#L292-L321

A stream client uses the [`route`](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_stream/docs/PROTOCOL.adoc#route) and [`partitions`](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_stream/docs/PROTOCOL.adoc#partitions) protocol commands to find out about the topology of a super stream. This is usually encapsulated in the library.

We haven't decided yet whether we'll introduce commands to manage super streams (declare/delete), but it's likely we will in the near future.
