### ISSUE TITLE
Add support for .NET Standard 2.0 NuGet packages similar to that of the RabbitMQ.Client library

### ISSUE THREAD

**Issue by israel-vieira** [rabbitmq/rabbitmq-stream-dotnet-client#318]
### Is your feature request related to a problem? Please describe.

Current RabbitMQ.Stream.Client NuGet package only supports .NET 6 and 7, which are the latest and greatest versions of .NET but not yet adopted by everyone. This is limiting the usability of the RabbitMQ Streams Client and consequently adoption by older projects.

### Describe the solution you'd like

Add support for .NET Standard 2.0 in [RabbitMQ.Stream.Client](https://www.nuget.org/packages/RabbitMQ.Stream.Client#supportedframeworks-body-tab) NuGet packages.

### Describe alternatives you've considered

Using the standard RabbitMQ Client with AMQP by treating the stream as a queue, but with possible performance degradation and without full support on stream features.

**Comment by lukebakken** [comment]
@israel-vieira I attempted to do this at one point in the past (a year ago, maybe). As you can expect, the library currently uses so many .NET 6/7 features as well as new C# language features that the amount of work to support `netstandard2.0` is not worth the return on investment at this time.

If the community wishes to step up and do this, great. A [RabbitMQ customer](https://rabbitmq.com/#support) can also request this work to be done and it would be given higher priority.

**Comment by israel-vieira** [comment]
@lukebakken Many thanks for your promptly reply to this issue with clear explanation and directions. The .NET6+ adoption will happen eventually on our side, but we need to overcome some hurdles to port legacy applications.
