### ISSUE TITLE
Expose Chunk info to MessageContext

### ISSUE THREAD

**Issue by andreasolazzo-b52** [rabbitmq/rabbitmq-stream-dotnet-client#331]
### Is your feature request related to a problem? Please describe.

In my use case, I need to start consuming from the last message (included) of a stream at a given time, assuming no one is publishing to the stream at the same time. 
At the moment, the closest option is to start consuming from the first message in the last chunk, but there's no way to know when the actual last message is reached. 

### Describe the solution you'd like

Looking at the `RawConsumer` implementation, the information on `Chunk` ID and the number of entries/records is [there](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/4cefb8424123bb7543a02dc591d4c9d07321496d/RabbitMQ.Stream.Client/RawConsumer.cs#L332), but it is not exposed to the client.
With that information available in the `MessageContext`, along with the message offset, it would be possible to start consuming from the first message of the last chunk and "ignore" messages until the last one is reached, calculating it based on the number of entries/records of the chunk itself. 

### Describe alternatives you've considered

One other option would be to add either the exact offset of the last message or the number of entries/records of the last chunk to the `StreamStats`.

**Comment by Gsantomaggio** [comment]
Thank you for reporting the issue. We will evaluate it as soon as possible.

**Comment by Gsantomaggio** [comment]
@francescopessina87 and his team will provide a PR for this issue. 

You can add the info to the context message.

**Comment by Gsantomaggio** [comment]
FYI: https://www.nuget.org/packages/RabbitMQ.Stream.Client/1.8.0-rc.3 
Please try the version and let me know

**Comment by francescopessina87** [comment]
@Gsantomaggio I tried the `1.8.0-rc.3` version and everything works as expected 👍
