### ISSUE TITLE
Set TCP connection name

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-stream-dotnet-client#35]
Set the TCP connection name  for producer/consumer/locator as the other clients:
![Screen Shot 2021-12-09 at 17 25 09](https://user-images.githubusercontent.com/386987/145435613-40ff7889-9902-4ad4-b6c5-f6197878b9be.png)

**Comment by Gsantomaggio** [comment]
Hi, @0UserName 
Thank you for looking into that.

The locator connection is a connection used to locate the resources across the cluster as for example locate the Queue Leader. 

for each:
```csharp
var system = await StreamSystem.Create(config);
```
there is a locator.

The locator connection can be called `dotnet-stream-locator`.

About producers and consumers I'd  do something like:
```csharp
        new ProducerConfig / ConsumerConfig
        {
        ......
        Name = "my-custom-name" <--- new field
            
```

If not specified can be called: `dotnet-stream-consumer` or `go-stream-producer`

**Comment by Gsantomaggio** [comment]
>Do you mean just [add](https://github.com/0UserName/rabbitmq-stream-dotnet-client/commit/b6bc3205edc6459b9396ab68045be4bc155dbfd0) ClientProvidedName

Yes

**Comment by 0UserName** [comment]
Added to {Producer|Consumer}Config. Created [PR](#66 ).

![Capture](https://user-images.githubusercontent.com/46850587/154132315-997bf959-1d37-4a10-857d-8da19b4bb2d3.PNG)

**Comment by Gsantomaggio** [comment]
closed via https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/66
