### ISSUE TITLE
Consumer connecting to leader node

### ISSUE THREAD

**Issue by francescopessina87** [rabbitmq/rabbitmq-stream-dotnet-client#351]
### Describe the bug

As stated in the blog post "Connecting to Streams", a good practice for producers and consumers should be the following:
- producers should always connect to leader nodes
- consumers should always connect to follower nodes

(see https://blog.rabbitmq.com/posts/2021/07/connecting-to-streams/#well-behaved-clients)

Looking at RawConsumer.cs, it connects to the cluster using the `LookupRandomConnection` method (here: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/main/RabbitMQ.Stream.Client/RawConsumer.cs#L205)

As stated in the comment of the method (here: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/c3d8e555be3154f873aeb4d7a3229e97004cce28/RabbitMQ.Stream.Client/RoutingClient.cs#L178) that method "Gets a random connection. The consumer can connect to a replica or leader.", which is contradictory to the "well behaved clients" recommendation.

Furthermore, trying that with a cluster behind a load balancer, my consumers always connect to the stream leader node.

Could it be fixed to follow the recommended best practices?

### Reproduction steps

Connect a consumer to a cluster and check to which node the client is connected to. This should never be a stream leader node.

### Expected behavior

When a consumer connects to a stream in a cluster should connect to one of the "followers" node of a stream.

**Comment by Gsantomaggio** [comment]
Grazie @francescopessina87 

Here the working in progress https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/352
