### ISSUE TITLE
No Connection Resilience when missing too many heartbeats

### ISSUE THREAD

**Issue by bastl98** [rabbitmq/rabbitmq-stream-dotnet-client#393]
### Describe the bug

Currently, the stream connection is not resilient when too many heartbeats are missed and there is a timeout on the connection close. 
All publishes of this connection result in a client timeout error and all consumers of this connection stop working.

There is also no reconnection attempt, because this error is processed as a "normal" connection close. A manual reconnection attempt is also not possible, because all properties which could be used to check if there is a need for a reconnection attempt still indicate that the connection is available:
![image](https://github.com/user-attachments/assets/25c0e736-97f9-4b1e-aeed-f9a2bd561e5a)

### Reproduction steps

1.Start RMQ Cluster with 3 nodes (docker)
2.Create a stream system and a consumer with the client lib which connects to one of the nodes (lower heartbeat interval for testing)
![image](https://github.com/user-attachments/assets/8dc7bc33-fca3-4352-8f4e-9dca288487f7)
3.Pause the the node to which the consumer is connected
4.Wait for 4 Heartbeats
5. The following errors are produced by the client lib
![image](https://github.com/user-attachments/assets/d2ed0f64-b407-46cc-be89-4bf5c97df279)
6. The consumer stops working but the method .IsOpen() still returns true

### Expected behavior

The timeout error should not result in a "normal" connection close, this should lead to a reconnection attempt by the library itself.

### Additional context

Our RMQ Cluster has version 3.13.0 and our client lib has version 1.8.2

**Comment by bastl98** [comment]
I have adapted the BestPracticesClient for reproduction purposes (Logging in Consumer Callback and lowered hearbeat timespan). I have attatched the BestPracticesClient and appsettings.json which i have used to reproduce the error.

Here´s the link to the repo: [https://github.com/bastl98/rmq-bug-source.git](url)

Steps:
1. Start the client and wait until the consumer starts consuming
2. Pause the rmq container the consumer is connected to and wait until the heartbeat threshhold is reached
3. The connection is closed "normal" because of a timeout in the connection close procedure
4. When restarting the conatiner, the consumer and the connection will not recover but the consumer is still open

**Comment by Gsantomaggio** [comment]
@bastl98 Thank you for reporting the issue.

The library is working properly. 
It is precisely the scope for the heartbeat to close the client when the client does not receive the "alive" from the server. 

The problem here is the Consumer with the status `IsOpen == true` is even closed and should be set as closed.
The correct status should be `IsOpen == false`

**Comment by bastl98** [comment]
Will the consumer handling in this case be fixed in the foreseeable future?

**Comment by Gsantomaggio** [comment]
>Will the consumer handling in this case be fixed in the foreseeable future?

What do you mean? In this case, the consumer will be closed.

**Comment by Gsantomaggio** [comment]
@bastl98 Ok you were right. The heartbeat should be considered as `Unexpected` close so the client should try to reconnect.

**Comment by bastl98** [comment]
@Gsantomaggio unfortunatly, the error is not resolved.
I think the problem now is in the Dispose method of the connection.

When the heartbeats are missed, the Close method of the client is called, this method sets the close status of the connection to unexpected.

But in the Dispose Method of the connection, which is called in any case at the of the Close method, the close reason is set to normal again.

![Screenshot 2024-10-21 051124](https://github.com/user-attachments/assets/cbc5248f-9a85-47f3-8dd5-ab350065997f)

**Comment by Gsantomaggio** [comment]
Uhm you are right. I need to review the status part. At the moment is a bit weak. I planed to refactor it for the version 2.0 but I will see if I can do something for the version 1.x without breaking changes

**Comment by Gsantomaggio** [comment]
@bastl98 Can you please test the last [commit](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/394/commits/f4c027bb26df17a4ab2bca4363f208c26ec3b01c)?

**Comment by bastl98** [comment]
@Gsantomaggio now it works. Thanks!
