### ISSUE TITLE
StreamSystem.CreateProducer never returns on authentication errors

### ISSUE THREAD

**Issue by motmot80** [rabbitmq/rabbitmq-stream-dotnet-client#41]
# Environment:
- RabbitMQ: 3.9.10
- Erlang: 24.1.7

# Reproduction steps:
Use `StreamSystem.CreateProducer` on a stream which the user cannot access.

Log example:
```
2021-12-16 19:24:36.615000+01:00 [warning] <0.23496.15> User 'guest' can only connect via localhost
2021-12-16 19:24:36.616000+01:00 [warning] <0.23496.15> Closing socket #Port<0.7840>. Invalid transition from authenticating to failure.
```

# Expected:
Exception describing a authorization problem.

# Actual:
The method never returns.

**Comment by Gsantomaggio** [comment]
The client does not handle `responseCodeAuthenticationFailureLoopback` error. 
Working on it

**Comment by Gsantomaggio** [comment]
closed via https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/commit/e6e51cc395287cfd960681f79aa5e56c054db478 


@motmot80 can you please try with  `1.0.0-alpha6`? thank you

**Comment by motmot80** [comment]
@Gsantomaggio  Seems to work with `1.0.0-alpha6` now.

**Producer exception:**
`RabbitMQ.Stream.Client.AuthenticationFailureLoopback: 'guest'`

**Consumer aggregate exception:**
Inner exception: `AuthenticationFailureLoopback: guest`

Thanks a lot and keep up the good work!
