### ISSUE TITLE
Consume on all streams

### ISSUE THREAD

**Issue by rsulab** [rabbitmq/rabbitmq-stream-dotnet-client#48]
How to consume on all streams in StreamSystem?

**Comment by Gsantomaggio** [comment]
See the getting started example. You need to create one consumer for stream: 
```
// Create a consumer
var consumer = await system.CreateConsumer(
    new ConsumerConfig
    {
        Reference = Guid.NewGuid().ToString(),
        Stream = stream,
        // Consume the stream from the beginning 
        // See also other OffsetSpec 
        OffsetSpec = new OffsetTypeFirst(),
        // Receive the messages
        MessageHandler = async (consumer, ctx, message) =>
        {
            Console.WriteLine($"message: {Encoding.Default.GetString(message.Data.Contents.ToArray())} - consumed");
            await Task.CompletedTask;
        }
    });
```

**Comment by rsulab** [comment]
> See the getting started example. You need to create one consumer for stream:
> 
> ```cs
> // Create a consumer
> var consumer = await system.CreateConsumer(
>     new ConsumerConfig
>     {
>         Reference = Guid.NewGuid().ToString(),
>         Stream = stream,
>         // Consume the stream from the beginning 
>         // See also other OffsetSpec 
>         OffsetSpec = new OffsetTypeFirst(),
>         // Receive the messages
>         MessageHandler = async (consumer, ctx, message) =>
>         {
>             Console.WriteLine($"message: {Encoding.Default.GetString(message.Data.Contents.ToArray())} - consumed");
>             await Task.CompletedTask;
>         }
>     });
> ```

I mean i have 10 streams - "stream1", "stream2" and so on

i want create one consumer for all streams and i dont know stream names

**Comment by Gsantomaggio** [comment]
> I want create one consumer for all streams

You need a consumer for stream. You can use the same consumer for multiple streams.

> i dont know stream names

The stream name is mandatory to create a consumer. 

To know all the streams you can use the [HTTP API](https://rawcdn.githack.com/rabbitmq/rabbitmq-server/v3.9.11/deps/rabbitmq_management/priv/www/api/index.html)  `/api/queues` and filter for type `stream`
