### ISSUE TITLE
Overload the Data struct's constructor to accept an array of bytes

### ISSUE THREAD

**Issue by LiamMcRoe** [rabbitmq/rabbitmq-stream-dotnet-client#54]
The Data struct currently has a single constructor, accepting a `ReadOnlySequence<byte>`.
The current suggested usage for construction of a `Data` object is to construct a `ReadOnlySequence<byte>` from a `byte[]`, and then pass this `ReadOnlySequence<byte>` to the constructor of the `Data` struct:

```
var readonlySequence = new ReadOnlySequence<byte>(Encoding.UTF8.GetBytes($"hello {i}"));
var message = new Message(new Data(readonlySequence));
```
This chain of calls is likely to have to be implemented whenever messages are being created.

I believe a cleaner approach would be to provide an overloaded `Data` constructor that accepts a `byte[]`.
The body of this constructor would then create the `ReadOnlySequence<byte>` and pass this to the existing `Data` constructor.
The above code could then be reduced to:

```
var message = new Message(new Data(Encoding.UTF8.GetBytes($"hello {i}")));
```
or similar, whenever a message is to be created from an array of bytes.

**Comment by Gsantomaggio** [comment]
you can already do something like:
```csharp
    var message = new Message(Encoding.UTF8.GetBytes("hello world"));
```

**Comment by Gsantomaggio** [comment]
I [changed](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/commit/7ee4f3e6d5f55cfb04dc02755fb9b2d3430d67ae) the Getting started. Thank you for reporting btw. 

Let me know if it is enough.

**Comment by LiamMcRoe** [comment]
Ahh my bad, I hadn't realised there was a constructor like that for the Message. Looks good, thanks.
