### ISSUE TITLE
Use same stream default parameters when declaring a stream as Java and Go do

### ISSUE THREAD

**Issue by MarcialRosales** [rabbitmq/rabbitmq-stream-dotnet-client#62]
When the Java and Go stream clients declare a stream, they include the parameter `queue-leader-locator` with the default value `least-leaders`. 

At present, the .Net client does not provide this parameter therefore when it tries to redeclare a stream which has been previously declared by either Go or Java, it gets a Precondition validation error.

**Comment by Gsantomaggio** [comment]
closed via https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/commit/78e78cdf7f2c1b6ce653dd730ff921fcf0df17e9
