### ISSUE TITLE
Connection flow

### ISSUE THREAD

**Issue by CasperTDK** [rabbitmq/rabbitmq-stream-dotnet-client#9]
Hi

How should I handle the client connection lifecycle? 

I believe rabbitmq AMQP sdk client uses a connection pool, can reestablish connections etc. 

To be specific. I have a handler that gets some data, transforms it and adds to a stream. Should the handler have a transiant stream client and call Client.Close when each task is finished or should it be singleton?

I also have a singleton service that actively consumes from the stream - should I create a new client/connection periodically or can it run "forever". 

Please provide some guidance for good connection handling :) 

Thanks!

**Comment by kjnilsson** [comment]
I'd keep long running connections. The protocol isn't optimised for fast connection establishment.

The general idea for the client is that we'll have a higher level API that deals with Producers and Consumers and underneath these are backed by the Client class and that level handles re-connections, meta data resolution etc.

I'm hoping to start drafting that part of the API soon.

**Comment by CasperTDK** [comment]
@kjnilsson Could this work tempoarily or do you see any big red flags? 

```csharp
 public class StreamClientInstaller : IServiceCollectionInstaller
  {
    public void Install(IServiceCollection services)
    {
      var logger = services.BuildServiceProvider().GetRequiredService<ILogger<StreamClientInstaller>>();
      logger.LogInformation(nameof(StreamClientInstaller));
      services.AddSingleton<ClientFactory>();
      services.AddTransient(provider =>
      {
        var clientFactory = provider.GetRequiredService<ClientFactory>();
        return clientFactory.GetClient();
      });
    }
  }

  public class ClientFactory
  {
    private readonly AppSettings appSettings;
    private readonly ILogger<ClientFactory> logger;
    private Client client;

    public ClientFactory(AppSettings appSettings, ILogger<ClientFactory> logger)
    {
      this.appSettings = appSettings;
      this.logger = logger;
    }

    public async Task<Client> GetClient()
    {
      if (client == null || client.IsClosed)
      {
        client = await CreateClient();
        return client;
      }

      try
      {
        await client.QueryMetadata(new[] { appSettings.StreamName });
      }
      catch (Exception e)
      {
        logger.LogWarning(e, "Error querying rabbitMQ. Creating new client");
        try
        {
          await client.Close("done");
        }
        catch (Exception)
        {
          // ignored
        }

        client = await CreateClient();
      }

      return client;
    }

    private async Task<Client> CreateClient()
    {
      var rabbitMqUrl = new UriBuilder(appSettings.RabbitMQUrl);
      IPAddress ipAddress = (await Dns.GetHostEntryAsync(rabbitMqUrl.Host)).AddressList.FirstOrDefault() ??
                            IPAddress.Loopback;
      var ipEndPoint = new IPEndPoint(ipAddress, 5552);

      var clientParameters = new ClientParameters
      {
        UserName = rabbitMqUrl.UserName,
        Password = rabbitMqUrl.Password,
        Endpoint = ipEndPoint
      };
      return await Client.Create(clientParameters);
    }
  }
```

I would then inject Client into my transient handlers and ClientFactory my longrunning service

**Comment by kjnilsson** [comment]
That looks fine to me. I haven't written services in .NET for years

**Comment by CasperTDK** [comment]
@Gsantomaggio Any thoughts on this? I see you have implemented some dispose handling.
i.e thoughts on connectionpool, long living connection flow etc.

**Comment by Gsantomaggio** [comment]
@CasperTDK I think that the new [reliable implementation](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client#reliable) covers this part.

Connections are automatically handled. 

I close this issue. Let us know if reliable can work for you or if there is something missing.
